# General Settings

# Whether the commit message includes body
includeBody=true

# Enable usage statistics tracking
useStats=false

# Path to custom system prompt file
systemPromptPath=commit-prompt.md

# Model-Specific Settings
[ANTHROPIC]
model[]=claude-haiku-4-5
