#!/usr/bin/env python3


def is_vanilla() -> bool:
    import builtins
    import sys

    return (
        not hasattr(builtins, "__IPYTHON__") and "bpython" not in sys.argv[0]
    )


def setup_history():
    import atexit
    import os
    import readline
    from pathlib import Path

    if state_home := os.environ.get("XDG_STATE_HOME"):
        state_home = Path(state_home)
    else:
        state_home = Path.home() / ".local" / "state"

    history: Path = state_home / "python_history"

    readline.read_history_file(str(history))
    _ = atexit.register(readline.write_history_file, str(history))


if is_vanilla():
    setup_history()
