#!/usr/bin/env zsh

set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

usage() {
  cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v]

Uses llm <https://llm.datasette.io> to generate a CLI command.

Available options:

-e, --explain   Explain what the output does
-h, --help      Print this help and exit
-v, --verbose   Print script debug info
EOF
  exit
}

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
}

setup_colors() {
  # shellcheck disable=SC2034
  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
    readonly NOFORMAT='\033[0m'
    readonly RED='\033[0;31m'
    readonly GREEN='\033[0;32m'
    readonly ORANGE='\033[0;33m'
    readonly BLUE='\033[0;34m'
    readonly PURPLE='\033[0;35m'
    readonly CYAN='\033[0;36m'
    readonly YELLOW='\033[1;33m'
  else
    readonly NOFORMAT=''
    readonly RED=''
    readonly GREEN=''
    readonly ORANGE=''
    readonly BLUE=''
    readonly PURPLE=''
    readonly CYAN=''
    readonly YELLOW=''
  fi
}

msg() {
  echo >&2 -e "${1-}"
}

die() {
  local msg=$1
  local code=${2-1} # default exit status 1
  msg "$msg"
  exit "$code"
}

parse_params() {
  while :; do
    case "${1-}" in
      -e | --explain) EXPLAIN=1 ;;
      -h | --help) usage ;;
      -v | --verbose) set -x ;;
      --no-color) NO_COLOR=1 ;;
      -?*) die "Unknown option: $1" ;;
      *) break ;;
    esac
    shift
  done

  args=("$@")

  return 0
}

parse_params "$@"
setup_colors

# shellcheck disable=SC2068
if command -v llm &>/dev/null; then
  if [[ -n "${EXPLAIN-}" ]]; then
    explain_text="Also, provide a detailed description of how the command works."
    format_text="Description: <insert_description_here>\nThe description should be in English."
  else
    explain_text=""
    format_text="Don't enclose the command with extra quotes or backticks."
  fi

  # shellcheck disable=SC2116
  output=$(llm --system "You're a command line tool that generates CLI commands for the user." \
    "Instructions: Write a CLI command that does the following: $(echo ${args[@]}). Make sure the command is correct and works on ${DISTRO} using ${SHELL}. ${explain_text}\n\Format: ${format_text}\n\Make sure you use the format exactly as it is shown above. Never output any markdown, code blocks or code fences. Do output line breaks.")

  if [[ -n "${EXPLAIN-}" ]]; then
    msg "$output"
  else
    echo -n "$output"
  fi
else
  die "llm is required but not installed. Aborting."
fi
