#!/usr/bin/env zsh

set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

usage() {
  cat >&2 <<EOF
Usage: $(basename "${0}") [-h] [-v]

Uses llm <https://llm.datasette.io> to generate a CLI command.

Available options:

-e, --explain   Explain what the output does
-h, --help      Print this help and exit
-v, --verbose   Print script debug info
EOF
  exit
}

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
}

setup_colors() {
  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
    NOFORMAT='\033[0m'
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    ORANGE='\033[0;33m'
    BLUE='\033[0;34m'
    PURPLE='\033[0;35m'
    CYAN='\033[0;36m'
    YELLOW='\033[1;33m'
  else
    NOFORMAT=''
    RED=''
    GREEN=''
    ORANGE=''
    BLUE=''
    PURPLE=''
    CYAN=''
    YELLOW=''
  fi
  # shellcheck disable=SC2034
  readonly NOFORMAT RED GREEN ORANGE BLUE PURPLE CYAN YELLOW
}

msg() {
  echo >&2 -e "${1-}"
}

die() {
  local msg=${1}
  local code=${2-1} # default exit status 1
  msg "${msg}"
  exit "${code}"
}

parse_params() {
  while :; do
    case "${1-}" in
      -e | --explain) EXPLAIN=1 ;;
      -h | --help) usage ;;
      -v | --verbose) set -x ;;
      --no-color) NO_COLOR=1 ;;
      -?*) die "Unknown option: ${1}" ;;
      *) break ;;
    esac
    shift
  done

  args=("${@}")

  return 0
}

parse_params "${@}"
setup_colors

readonly REQUIRED_BINARIES=("llm")
for bin in "${REQUIRED_BINARIES[@]}"; do
  if ! command -v "${bin}" >/dev/null 2>&1; then
    die "${bin} is required, exiting"
  fi
done

if [[ -n "${EXPLAIN-}" ]]; then
  explain_text="Also, provide a detailed description of how the command works."
  format_text="Description: <insert_description_here>
The description should be in English."
else
  explain_text=""
  format_text="Don't enclose the command with extra quotes or backticks."
fi

readonly API_KEY="op://Private/sgjddcuzvgu3qbpzqqw6tn5lw4/credential"
SYSTEM_PROMPT="You're a CLI tool that generates commands for the user."
readonly SYSTEM_PROMPT

read -r -d '' user_prompt <<EOF || true
Instructions: Write a CLI command that does the following: ${args[@]}.
Make sure the command is correct and works on ${DISTRO} using ${SHELL}.
${explain_text}
Format: ${format_text}
Make sure you use the format exactly as it is shown above.
Never output any markdown, code blocks or code fences.
Do output line breaks.
EOF

output=$(
  OPENAI_API_KEY="${API_KEY}" op run -- \
    llm --system "${SYSTEM_PROMPT}" "${user_prompt}"
)

if [[ -n "${EXPLAIN-}" ]]; then
  msg "${output}"
else
  echo -n "${output}"
fi
