#!/usr/bin/env bash
#
# Branch output:
#
# * release/v1.1    (13 days)    <John Doe>   add pretty_git_branch
#
# The time massaging regexes start with ^[^<]* because that ensures that they
# only operate before the first "<". That "<" will be the beginning of the
# author name, ensuring that we don't destroy anything in the commit message
# that looks like time.
#
# The log format uses } characters between each field, and `column` is later
# used to split on them. A } in the commit subject or any other field will
# break this.

set -Eeuo pipefail

readonly BRANCH_PREFIX="%(HEAD)"
readonly BRANCH_REF="%(color:red)%(color:bold)%(refname:short)%(color:reset)"
readonly BRANCH_HASH="%(color:yellow)%(objectname:short)%(color:reset)"
BRANCH_DATE="%(color:green)(%(committerdate:relative))%(color:reset)"
readonly BRANCH_DATE
BRANCH_AUTHOR="%(color:blue)%(color:bold)"
BRANCH_AUTHOR+="<%(authorname)>%(color:reset)"
readonly BRANCH_AUTHOR
readonly BRANCH_CONTENTS="%(contents:subject)"

BRANCH_FORMAT="${BRANCH_PREFIX}}${BRANCH_REF}}${BRANCH_HASH}}"
BRANCH_FORMAT+="${BRANCH_DATE}}${BRANCH_AUTHOR}}${BRANCH_CONTENTS}"
readonly BRANCH_FORMAT

show_git_head() {
  git l --max-count=1
  git show --patch --pretty="tformat:"
}

pretty_git_branch() {
  git branch --verbose --color=always --format=${BRANCH_FORMAT} ${1+"$@"} \
    | pretty_git_format
}

pretty_git_format() {
  # Replace (2 years ago) with (2 years)
  sed -r -e "s/(^[^<]*) ago\)/\1)/" \
    |
    # Replace (2 years, 5 months) with (2 years)
    sed -r \
      -e "s/(^[^<]*), [[:digit:]]+ .*months?\)/\1)/" \
    |
    # Line columns up based on } delimiter
    column -s '}' -t
}
