#!/usr/bin/env bash

set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

usage() {
  cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] path_to_file

Adds watermark to identification papers to prevent abuse.

Available options:

-h, --help      Print this help and exit
-v, --verbose   Print script debug info
EOF
  exit
}

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
}

setup_colors() {
  # shellcheck disable=SC2034
  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
    readonly NOFORMAT='\033[0m'
    readonly RED='\033[0;31m'
    readonly GREEN='\033[0;32m'
    readonly ORANGE='\033[0;33m'
    readonly BLUE='\033[0;34m'
    readonly PURPLE='\033[0;35m'
    readonly CYAN='\033[0;36m'
    readonly YELLOW='\033[1;33m'
  else
    readonly NOFORMAT=''
    readonly RED=''
    readonly GREEN=''
    readonly ORANGE=''
    readonly BLUE=''
    readonly PURPLE=''
    readonly CYAN=''
    readonly YELLOW=''
  fi
}

msg() {
  echo >&2 -e "${1-}"
}

die() {
  local msg=$1
  local code=${2-1} # default exit status 1
  msg "$msg"
  exit "$code"
}

parse_params() {
  while :; do
    case "${1-}" in
      -h | --help) usage ;;
      -v | --verbose) set -x ;;
      --no-color) NO_COLOR=1 ;;
      *) break ;;
    esac
    shift
  done

  args=("$@")

  # check required params and arguments
  [[ ${#args[@]} -eq 0 ]] && usage

  return 0
}

parse_params "$@"
setup_colors

required_binaries=("magick")
for bin in "${required_binaries[@]}"; do
  if ! command -v "$bin" >/dev/null 2>&1; then
    die "$bin is required, exiting"
  fi
done

msg "Name of organisation?"
read -r ORG
msg "For what purpose can this organisation use this document?"
read -r PURPOSE

magick "$1" \
  \( -background none -pointsize 48 -fill "rgba(10,20,30,0.30)" label:"Copy for $ORG\nPurpose: $PURPOSE\nDate: $(date +'%Y-%m-%d')" -font Skia -rotate 20 -write mpr:tile +delete \) \
  \( +clone -tile mpr:tile -draw "color 0,0 reset" \) \
  -compose over -composite -strip -interlace Plane -gaussian-blur 0.05 -quality 70% "$1.watermarked.jpg"
