#!/usr/bin/env bash

# @TODO everything

set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

usage() {
  cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v]

Runs maintenance on macOS.

Available options:

-h, --help      Print this help and exit
-v, --verbose   Print script debug info
EOF
  exit
}

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
}

setup_colors() {
  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
    NOFORMAT='\033[0m'
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    ORANGE='\033[0;33m'
    BLUE='\033[0;34m'
    PURPLE='\033[0;35m'
    CYAN='\033[0;36m'
    YELLOW='\033[1;33m'
  else
    NOFORMAT=''
    RED=''
    GREEN=''
    ORANGE=''
    BLUE=''
    PURPLE=''
    CYAN=''
    YELLOW=''
  fi
  # shellcheck disable=SC2034
  readonly NOFORMAT RED GREEN ORANGE BLUE PURPLE CYAN YELLOW
}

msg() {
  echo >&2 -e "${1-}"
}

die() {
  local msg=${1}
  local code=${2-1} # default exit status 1
  msg "${msg}"
  exit "${code}"
}

parse_params() {
  while :; do
    case "${1-}" in
      -h | --help) usage ;;
      -v | --verbose) set -x ;;
      --no-color) NO_COLOR=1 ;;
      -?*) die "Unknown option: ${1}" ;;
      *) break ;;
    esac
    shift
  done

  return 0
}

parse_params ${1+"$@"}
setup_colors

REQUIRED_BINARIES=(
  "brew"
  "bun"
  "docker"
  "gcloud"
  "gh"
  "git"
  "mas"
  "mise"
  "npm"
  "op"
  "tldr"
)
for bin in "${REQUIRED_BINARIES[@]}"; do
  if ! command -v "${bin}" >/dev/null 2>&1; then
    die "${bin} is required, exiting"
  fi
done

# Wrapper for brew via 1Password plugin
brew() {
  op plugin run -- brew "$@"
}

# Wrapper for gh via 1Password plugin
gh() {
  op plugin run -- gh "$@"
}

msg "${BLUE}Updating from Mac App Store${NOFORMAT}"
mas upgrade || true

msg "${BLUE}Updating Homebrew${NOFORMAT}"
brew update

msg "${BLUE}Updating brews${NOFORMAT}"
brew upgrade

msg "${BLUE}Updating casks${NOFORMAT}"
brew upgrade --cask

msg "${BLUE}Pruning stale dependencies${NOFORMAT}"
brew autoremove

msg "${BLUE}Cleaning Homebrew${NOFORMAT}"
brew cleanup

msg "${BLUE}Verifying Homebrew integrity${NOFORMAT}"
brew doctor || true

msg "${BLUE}Updating gcloud${NOFORMAT}"
gcloud components update

msg "${BLUE}Updating tldr${NOFORMAT}"
tldr --update

msg "${BLUE}Updating dotfile git repositories${NOFORMAT}"
cd "${ZDOTDIR}/.zprezto" || true
git pull
git submodule sync --recursive
git submodule update --init --recursive
cd "${ZDOTDIR}/.zprezto/contrib" || true
git pull
git submodule sync --recursive
git submodule update --init --recursive
cd "${ZDOTDIR}/.zsh-defer" || true
git pull
cd "${HOME}" || true

msg "${BLUE}Pruning docker${NOFORMAT}"
docker system prune --all --force

msg "${BLUE}Updating gh extensions${NOFORMAT}"
gh extension upgrade --all

msg "${BLUE}Upgrading mise tools${NOFORMAT}"
mise upgrade

msg "${BLUE}Pruning old mise tool versions${NOFORMAT}"
mise prune

msg "${BLUE}Updating global bun packages${NOFORMAT}"
while IFS= read -r pkg; do
  bun add -g "$pkg" 2>&1 | tail --lines 1
done <"${HOME}/Library/Application Support/bun/default-bun-packages"

msg "${BLUE}Updating global gem packages${NOFORMAT}"
for v in $(mise ls ruby --installed | awk '{print $2}'); do
  while IFS= read -r gem; do
    "${HOME}/.local/share/mise/installs/ruby/${v}/bin/gem" update "${gem}" 2>&1 \
      | tail --lines 1
  done <"${HOME}/Library/Application Support/gem/default-gem-packages"
done

msg "${BLUE}Updating global go packages${NOFORMAT}"
while IFS= read -r pkg; do
  go install "${pkg}@latest" 2>&1 | tail --lines 1
done <"${HOME}/Library/Application Support/go/default-go-packages"

msg "${BLUE}Updating global npm packages${NOFORMAT}"
npm update --global

msg "${BLUE}Updating global pip packages${NOFORMAT}"
for v in $(mise ls python --installed | awk '{print $2}'); do
  "${HOME}/.local/share/mise/installs/python/${v}/bin/pip" install \
    --upgrade \
    --requirement \
    "${HOME}/Library/Application Support/pip/default-python-packages" 2>&1 \
    | tail --lines 3
done

msg "${BLUE}Clearing zsh completion cache${NOFORMAT}"
rm -rf "${XDG_CACHE_HOME:-${HOME}/.cache}/zsh/completions"
rm -f "${ZDOTDIR:-${HOME}}/.zcompdump"*

msg "${GREEN}Applications to update manually${NOFORMAT}"
brew list --cask -1 | xargs op plugin run -- brew info --cask | rg auto_updates
msg "Apple Books"
msg "GarageBand (sound library)"
msg "Xcode (components)"
msg "Wipr (definitions)"
mise outdated || true
